### ISSUE TITLE
dispatch fonksiyonu geliştirmesi

### ISSUE THREAD

**Issue by tufkan** [tayfunerbilen/prototurk-mvc#1]
Tayfun Hocam selamlar,

dispatch fonksiyonunda yanlızca belirtilen id ve url yerine sınırsız parametre alması için fonksiyonu değiştirdim, biraz karışık gibi oldu hocam ama size varken zaten toparlarsınız diye düşünüyorum :)

`        public static function dispatch()
        {
            $url = self::getUrl();
            $method = self::getMethod();
            $paramsData = null;
            $params = [];

            foreach (self::$routes[$method] as $path => $props) {
                $callback = $props['callback'];

                $newPath = null;
                $pathExploder = explode("/",$path);
                $urlExploder = explode("/",$url);

                foreach ($pathExploder as $item => $value){
                    if (str_contains($value,":")){
                        $newPath .= "/[0-9a-zA-Z-_]+";
                        $paramsData[] = $item;
                    }else{
                        if (!is_null($value) AND $value != ""){
                            $newPath .= "/$value";
                        }
                    }
                }

                if ($newPath == ""){
                    $newPath = "/";
                }

                $pattern = '#^' . $newPath . "$#";

                if (preg_match($pattern,$url)){
                    self::$hasRoute = true;

                    if (is_array($paramsData)){
                        foreach ($paramsData as $item) {
                            $params[] = $urlExploder[$item];
                        }
                    }

                    if (is_callable($callback)) {
                        echo call_user_func_array($callback, $params);
                    } elseif (is_string($callback)) {

                        [$controllerName, $methodName] = explode('@', $callback);

                        $controllerName = '\Prototurk\App\Controllers\\' . $controllerName;
                        $controller = new $controllerName();
                        echo call_user_func_array([$controller, $methodName], $params);

                    }
                }

            }
            self::hasRoute();
        }`

**Comment by tayfunerbilen** [comment]
şimdilik `where()` metodu ekledim Route sınfına yeterli olacaktır, sonra bakarız daha esnek nasıl yapabileceğimize 👍
